version: 2
jobs:
  build:
    docker:
      - image: node:8-buster-slim

    steps:
      - checkout

      - run:
          name: install markdown-spellcheck
          command: npm i markdown-spellcheck -g

      - run:
          name: Spell check Markdown Files
          command: mdspell --ignore-numbers --report "**/*.md"


workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
