version: 2
jobs:
  build:
    docker:
      - image: debian:buster-slim

    steps:
      - checkout

      - run:
          name: Show directory contents
          command: ls -alh

      - run:
          name: Install aspell
          command: apt-get update && apt-get intall -y aspell

      - run:
          name: Check README.md
          command: aspell check ./README.md