version: 2
jobs:
  build:
    docker:
      - image: debian:buster-slim

    steps:
      - checkout

      - run:
          name: Show directory contents
          command: ls -alh

      - run:
          name: Install nodejs
          command: apt-get update && apt-get install -y nodejs

      - run:
          name: install markdown-spellcheck
          command: npm i markdown-spellcheck -get

      - run:
          name: Spell check Markdown Files
          command: mdspell "**/*.md"