version: 2
jobs:
  build:
    docker:
      - image: debian:buster-slim

    steps:
      - checkout

      - run:
          name: Show directory contents
          command: ls -alh
      - run:
          name: Get curl
          command: apt-get update && apt-get install curl -y

      - run:
          name: Fetch nodejs setup
          command: curl -sL https://deb.nodesource.com/setup_13.x | bash -

      - run:
          name: Install nodejs
          command: apt-get install -y nodejs

      - run:
          name: install markdown-spellcheck
          command: npm i markdown-spellcheck -g

      - run:
          name: Spell check Markdown Files
          command: mdspell "**/*.md"
